services:
  - type: web
    name: slot-booking-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://slot_booking_gef9_user:tRFkhdLP5yPBVauNPcHkWUREdr1xaGj7@dpg-d258532li9vc73f1askg-a/slot_booking_gef9
    healthCheckPath: /api/health 